### ISSUE TITLE
.egg file?

### ISSUE THREAD

**Issue by mattbze** [cbueche/ZenPacks.community.Fortinet#1]
Hi,

Forgive me if I am completely wrong on this, but shouldn't Zen Packs have .egg files for installation? I cannot see any for your release.

Thanks

**Comment by cbueche** [comment]
Hi,

Yes it should. I asked Zenoss how to integrate their build system but didn't really got an answer, probably because they were in the middle of their renaming / reorganization of their web site/zenpack repo. If you want to build an egg, you should clone the zenpack, and then use 
```
cd ZenPacks.community.Fortinet
python setup.py bdist_egg
```

**Comment by mattbze** [comment]
Excellent ill do that.

Thanks Charles

**Comment by mattbze** [comment]
That was successful, fully installed. We are testing on an 800C so ill let you know how it goes.

**Comment by mattbze** [comment]
Hi Cbueche

I can confirm this Zenpack works well as expected on Fortigate 800C

Kr
Matthew

**Comment by cbueche** [comment]
Hey Matthew,

thanks for the feedback, I updated the README.

Kind regards,
Charles
